# Annotations is useful mainly in 
# kubectl rollout history deployment/nginx-deployment

apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
  labels:
    app: nginx
  annotations:
   "kubernetes.io/change-cause" : "update the nginx tag"

spec:
  replicas: 5
  selector:
      matchLabels:
          app: nginx

  template:
     metadata:
        labels:
           app: nginx

     spec:
       containers:
       - name: nginx
         image: nginx:1.27.0-alpine
         ports:
         - containerPort: 80
